Change password to passwd in for making connection
    return Connection(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'password'
Due to this exception, need to change password to passwd for making connection.